# Generated by Django 5.0.4 on 2024-04-22 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('photos', '0002_petphoto_created_at_petphoto_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='pet_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='photos.petphoto'),
        ),
        migrations.AlterField(
            model_name='photolike',
            name='pet_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='likes', to='photos.petphoto'),
        ),
    ]
